#+title: Ethan Goan
#+description: Site for sharing some of my work
#+SUBTITLE:
#+META_TYPE: website

* empty
:PROPERTIES:
:CUSTOM_ID: empty
:UNNUMBERED: notoc
:END:


I am a research fellow at [[https://www.qut.edu.au/][QUT]] in the school of Electrical Engineering and Robotics, where I also completed my PhD in 2024 and my undergraduate in Electrical Engineering. My research focuses on uncertainty quantification in computer vision, machine learning and biomechanics. I have interests in statistics, embedded systems, Emacs, and much more which I may/may not occasionally write about.

You can contact me at: ej[dot]goan[at]qut[dot]edu[dot]au
#+begin_export html
<br>
<hr style="margin-bottom:0;"/>
#+end_export
** Publications

W. Xiao, E. Goan, R. Santa Cruz, D. Ahmedt-Aristizabal, O. Salvado, C. Fookes, and L. Lebrat. In depth
we trust: Reliable monocular depth supervision for gaussian splatting. In Proceedings of the IEEE/CVF
Conference on Computer Vision and Pattern Recognition, 2026. [[https://arxiv.org/abs/2604.05715][[paper]]]

A. Pemasiri, E. Goan, G. Lichtwark, R. Schuster, L. Kelly, and C. Fookes. Biomechanically accurate gait
analysis: A 3d human reconstruction framework for markerless estimation of gait parameters. In IEEE
International Symposium on Biomedical Imaging (ISBI), 2026. [[https://arxiv.org/pdf/2603.02499][[paper]]]

A. Pemasiri, Z. Huang, F. Williams, E. Goan, S. Denman, T. Martin, and C. Fookes. Automatic radar signal
detection and fft estimation using deep learning. In 17th International Conference on Signal Processing
and Communication Systems. IEEE, 2024. [[[https://arxiv.org/pdf/2402.19073][paper]]]

E. Goan and C. Fookes. Uncertainty in real-time semantic segmentation on embedded systems. In
Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition Workshops [[https://arxiv.org/abs/2301.01201][[paper]]] [[[https://github.com/egstatsml/eu-seg][code]]] [[file:assets/eu_errata/errata.pdf][[errata]]]

E. Goan, D. Perrin, K. Mengersen, and C. Fookes. Piecewise deterministic markov processes for bayesian
neural networks. In Uncertainty in Artificial Intelligence, 2023. [[https://arxiv.org/abs/2302.08724][[paper]]] [[https://github.com/egstatsml/tpdmp][[code]]] [[file:assets/pdmp_errata/errata.pdf][[errata]]]

O. Tursun, S. Denman, S. Sridharan, E. Goan, and C. Fookes. An efficient framework for zero-shot
sketch-based image retrieval. Pattern Recognition, 126:108528, 2022. [[https://arxiv.org/pdf/2102.04016][[paper]]]

S. K. Sieberts, J. Schaff, M. Duda, B. Á. Pataki, M. Sun, P. Snyder, J.-F. Daneault, F. Parisi, G. Costante, U.
Rubin, and others. Crowdsourcing digital health measures to predict parkinson’s disease severity: the
parkinson’s disease digital biomarker dream challenge. NPJ digital medicine, 4(1):53, 2021. [[https://www.nature.com/articles/s41746-021-00414-7][[paper]]]

E. Goan and C. Fookes. Bayesian neural networks: An introduction and survey. Case Studies in Applied
Bayesian Data Science 2020. [[https://arxiv.org/pdf/2006.12024][[paper]]] [[[file:assets/bayes_book_errata/errata.pdf][errata]]]

T. Schaffter, D. S. Buist, C. I. Lee, Y. Nikulin, D. Ribli, Y. Guan, W. Lotter, Z. Jie, H. Du, S. Wang, and
others. Evaluation of combined artificial intelligence and radiologist assessment to interpret screening
mammograms. JAMA network open, 2020. [[https://watermark02.silverchair.com/schaffter_2020_oi_200024.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAAyMwggMfBgkqhkiG9w0BBwagggMQMIIDDAIBADCCAwUGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM6YtCu-yoIQ2jzI8KAgEQgIIC1ou6-bjFiUdNi07Qq66n8PwFxiEwsCmyTXeTOcwOej7ppQFerOdJst9vBx32cBzUerBOlzjnhKERLOVYJudD00Ee_zY_JKV8WDZy63dbuRUAy9Z0wx6KLvIFjYQAmF6HlZ-37mHvFfX5ASJcXGOPVEJM-w0yhNw1HQK_pQ0R_GkelUbpBIutzF7-tsyKD-uxDkciwLZTfXdtBrCMbmou_aqACPHzdZhLhE-OacbQ3F-Cm4H4xHpwPhdGx1VQIr11xBX_YeGlLIQgHjY1oQ4rup8odEEA1QjH9B6FDqbd0Bfp_79GTJxQaNobmMfQOGuQS-lc8bOm0N04kXxEjP4wmq8R_gN6hujHTwmnBxeiualtm2WRbg_GXsHmjVzgyGGkSAoEq-6nAtW-JmtIw6kpT5DsubZHcqggqVZ4DyF0rPn4lDmRn7CCjdfgvMYp3TdxOKPaPhRzAGIQBASgxytUV7LOy6U-dTt4F_8Ohu8PtVyLPZnh_flfe7sSXucqhWyp0gbkpPT6xwZRRUiWNcQZTipyNxg5ZZ4L_I3u58PLfQytHyubF8BTNvUOnd49zhOMOVYor5FfMQ2L1u13VI-rt5GVieQaDh7fw0uFb5L8i_LEdTZ1-WdY7cBFwRFYbGUB-UC6iZnQodTEoR-EF0aMGQv7ZpGeBbZBZ8ch3_hA5E2Y68WCPeZuZci9TLAMth0489O39gTRt6AdasT00Np5BuIJAnqPs0SIDYRR5IcYSQRyl7xNNNbUjoUh9Svw-AwHtRzcNR32R4MS_QscBcvgEDyOj0fEZb48sOAR_c9NibHfwrffUf4Tr-NtAO9u6bSV6O7m5XlwZ72Shnacri-Jnp-4GPa7FS4GqluGfL8mNbMFyG8aHqWATNu6MD7_RAM6jvr38PvubOzDotSJ_DfC2_7yteeoHIujetOLyRLzk5CJtXK-RQ5DiRJJ3AVoFlVU5dxgCzibyw][[paper]]]

P. Moghadam, D. Ward, E. Goan, S. Jayawardena, P. Sikka, and E. Hernandez. Plant disease detection
using hyperspectral imaging. In 2017 International Conference on Digital Image Computing: Techniques
and Applications (DICTA), pages 1–8. IEEE, 2017. [[https://ieeexplore.ieee.org/abstract/document/8227476/][[paper]]]

R. Arablouei, E. Goan, S. Gensemer, and B. Kusy. Fast and robust pushbroom hyperspectral imaging via dmd-based scanning.
In Novel Optical Systems Design and Optimization XIX, SPIE, 2016. [[https://arxiv.org/pdf/1608.00361][[paper]]]

E. Goan, Practical Uncertainty in Neural Networks, PhD Thesis, Queensland University of Technology, 2024. [[[https://eprints.qut.edu.au/246038/][thesis]]]
